[package]
name = "@CRATE_NAME@"
version = "0.1.0"
edition = "2024"
authors = ["@AUTHOR_NAME@ <@AUTHOR_EMAIL@>"]
repository = "https://github.com/DoctorDalek1963/@REPO_NAME@"
license = "GPL-3.0-only"
publish = false

[dependencies]
